Modularisation ensemble
JinraeKim/ContinuousTimePolicyGradients.jl pull request #13
Opened 2021-12-15 23:58 UTC by nhcho91

2021-12-16 02:38 UTC, JinraeKim commented
I'm bz this week due to conference; will take a look at it later.

2021-12-16 07:05 UTC, JinraeKim requested changes
1) If we need "off-the-shelf" function for constructing a CTPG algorithm, why don't we provide the function for a single scenario first?
    - The ensemble seems a functionality for multiple scenario simulation. Is it training approximations (e.g., neural networks) simultaneously? If not, it would be better to open people's choice to perform parallel simulation. For example, I prefer [`Transducers.tcollect`](https://github.com/JuliaFolds/Transducers.jl) syntax, and in this regard, it's redundant.
2) Why is the name "struct_CTPG"? How about `construct_CTPG` or some thing like that?


FWIW, I agree that we need once an off-the-shelf function to construct a CTPG algorithm very conveniently. However, we will have to focus on defining appropriate types and structures of this package for CTPG later.

2021-12-16 07:05 UTC, JinraeKim commented on main/main_struct_CTPG_ensemble_autopilot.jl
> +include("../src/struct_CTPG.jl")
```suggestion
using ContinuousTimePolicyGradients
```

2021-12-16 07:05 UTC, JinraeKim commented on src/struct_CTPG.jl
> +# end
clear the commented out texts

2021-12-16 07:05 UTC, JinraeKim commented on src/struct_CTPG.jl
> +        loss_history[iterator_learning] = loss
DO NOT use global variables in `src`

2021-12-16 07:31 UTC, nhcho91 commented
- As long as I understood from reading diffeqflux.sciml.ai, DiffEqFlux simultaneously optimises NN parameters for multiple scenarios by solving an ensemble problem.
- One can choose to perform ensemble simulation either in serial or in parallel. The choice can be made through specification of ensemblealg.
- Good recommendation for the name of the function.

2021-12-16 08:31 UTC, JinraeKim requested changes
@nhcho91 Remove `Manifest.toml` from the files changed.

2021-12-16 08:32 UTC, JinraeKim commented on main/main_struct_CTPG_ensemble_autopilot.jl
> +include("../src/struct_CTPG.jl")
Why is it marked as resolved?

2021-12-17 01:43 UTC, nhcho91 commented
- The files are now corrected to remove errors in AD using Zygote.
- The implementation using EnsembleProblem can also be used to handle single ODE scenario, as long as the scenario generation part in main() follows certain structure resulting in a 1-dimensional vector of tuple of vectors for the predetermined list of ensemble cases.

2021-12-17 01:44 UTC, nhcho91 commented
> @nhcho91 Remove `Manifest.toml` from the files changed.

Manifest.toml has been deleted.

2021-12-17 01:45 UTC, nhcho91 commented on main/main_struct_CTPG_ensemble_autopilot.jl
> +include("../src/struct_CTPG.jl")
Sorry for my previous mistakes. Still a bit unfamiliar with the functionalities....

2021-12-18 20:17 UTC, nhcho91 commented
Several findings to report:

- sensealg = InterpolatingAdjoint( autojacvec = ReverseDiffVJP(true) ) is a lot faster than the case with ZygoteVJP().
- ReverseDiffVJP() can be used only for the ODE functions with no internal branching.
- ReverseDiffVJP() works without error only if the functions dynamics_plant(), dynamics_controller(), cost_xxx(), etc are not pre-specifying types for their inputs as Vector{Float32} or AbstractVector{Float32}. This is mainly due to the limitation of ReverseDiff related to the type specification of function inputs as arrays. See the [link](https://discourse.julialang.org/t/reversediff-function-type-specification/10350) or the page describing the limitations of ReverseDiff in its document for more details.

2021-12-19 02:44 UTC, JinraeKim commented
작업중인 것으로 보여서 draft 로 전환하였습니다

2021-12-19 10:15 UTC, nhcho91 commented
일단 마지막 커밋까지로 한 차례 일단락지어봅니다

2021-12-20 02:00 UTC, JinraeKim commented
@nhcho91 
아래 보이는 그림에 해당하는 것들을 표시해주시겠어요?
#6 을 참고하시면 좋을 것 같습니다.
이 PR 에 관한 이슈를 파서 link 시키면 더 좋고요~

![image](https://user-images.githubusercontent.com/43136096/146701244-50752868-3887-4d0c-ba2d-0ee6192d34b5.png)

2021-12-20 02:17 UTC, JinraeKim reviewed
유용하게 쓸 수 있지 않을까 기대됩니다 ㅎㅎ

2021-12-20 02:17 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    id_nominal = max(round(Int, dim_ensemble / 2), 1)
잘 이해가 안가는데, `id_nominal` 이 어떤 의미인지 알 수 있을까요?

2021-12-20 02:17 UTC, JinraeKim commented on main/main_struct_CTPG_ensemble_autopilot.jl
> +    scenario = ComponentArray(ensemble_list = ensemble_list, t_span = t_span, dim_x = dim_x, dim_x_c = dim_x_c)
```suggestion
    scenario = (; ensemble_list = ensemble_list, t_span = t_span, dim_x = dim_x, dim_x_c = dim_x_c)
```

`CTPG_train` 함수를 보아하니 ComponentArray 를 쓸 필요가 없어보입니다.
`NamedTuple` 로 바꾸는게 좋겠습니다 (이 경우, `using ComponentArrays` 도 삭제).

2021-12-20 02:17 UTC, JinraeKim commented on src/construct_CTPG.jl
> +            return [dx; dx_c; cost_running(t, x, y, u, r)]
이런 부분을 `ComponentArray` 로 처리하는게 더 적절해보입니다.

2021-12-20 02:17 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    prob_base = ODEProblem(fwd_dynamics(ensemble_list[id_nominal][2]), [ensemble_list[id_nominal][1]; zeros(Float32, dim_x_c + 1)], t_span, p_NN_0)
`ensemble_list` 의 각 원소도 `ComponentArray` 로 처리하면 가독성/확장성이 더 좋겠습니다 (인덱스 대신 key 로 처리할 수 있고, `src` 의 기능임에도 불구하고 `ensemble_list`를 외부에서 순서를 달리 줬을 때 작동할 수 있는 잠재적 오류가 우려됨).

2021-12-20 02:17 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    @unpack ensemble_list, t_span, dim_x, dim_x_c = scenario
`ensemble_list` 에 `dim_x`, `dim_x_c`, `t_span` 를 넣기보다는 각각을 `CTPG_train` 의 인자로 받는게 더 좋을 것 같네요.

2021-12-20 02:17 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    end
보아하니 `loss` 쪽에서는 여러 개의 앙상블에 대해 mean 으로 로스값을 구하고, 그 행위를 여러 번 반복하는 것으로 보입니다.
제가 코드를 제대로 이해한게 맞을까요?

만약 그럴 경우, `250` 이라는 learning iteration 숫자는 `CTPG_train` 의 인자로 받는 것이 좋겠습니다 (그런데 저건 `DiffEqFlux.sciml_train` 의 인자인 `max_iters` 랑 맞춰도 될 것 같네요?).

2021-12-20 02:17 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    result        = DiffEqFlux.sciml_train(loss, result_coarse.u, opt_2; cb = cb_progress, maxiters = 50)
1. `result_coarse`랑 `result` 가 어떤 차이인지 설명 가능할까요?
2. `max_iters` 등을 인자로 받기; 위 코멘트 참고

2021-12-20 02:17 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    solve_alg = Tsit5(), sense_alg = InterpolatingAdjoint(autojacvec = ZygoteVJP()), ensemble_alg = EnsembleThreads(), opt_1 = ADAM(0.01), opt_2 = LBFGS(), progress_plot = true, solve_kwargs...)
여기에 있는 `sense_alg` 나 `ensemble_alg` 등의 default key 는 없어도 될 것 같은데, 어떻게 생각하시나요?
(아마 DiffEq.jl 에서 기본값을 지원할 것 같은데...)

대신 관련 kwargs 를 묶어서 받고, line 39 쯤에 해당 kwargs를 넣는 식으로 하면 더 좋을 것 같습니다.

+) suggestion 처럼, docstring 을 만들어서 인자들 및 해당 함수의 기능에 대한 설명을 넣으면 좋을 것 같아요. [blank] 에 해당
```suggestion
"""
    CTPG_train(dynamics_plant::Function, dynamics_controller::Function, cost_running::Function, cost_terminal::Function, cost_regularisor::Function, policy_NN, scenario; 
    solve_alg = Tsit5(), sense_alg = InterpolatingAdjoint(autojacvec = ZygoteVJP()), ensemble_alg = EnsembleThreads(), opt_1 = ADAM(0.01), opt_2 = LBFGS(), progress_plot = true, solve_kwargs...)

[blank]
"""
function CTPG_train(dynamics_plant::Function, dynamics_controller::Function, cost_running::Function, cost_terminal::Function, cost_regularisor::Function, policy_NN, scenario; 
    solve_alg = Tsit5(), sense_alg = InterpolatingAdjoint(autojacvec = ZygoteVJP()), ensemble_alg = EnsembleThreads(), opt_1 = ADAM(0.01), opt_2 = LBFGS(), progress_plot = true, solve_kwargs...)
```

2021-12-20 02:41 UTC, JinraeKim commented
+) 이 PR 이 머지되고 나면 #14를 부탁드립니다.

2021-12-20 09:00 UTC, nhcho91 commented
> @nhcho91 아래 보이는 그림에 해당하는 것들을 표시해주시겠어요? #6 을 참고하시면 좋을 것 같습니다. 이 PR 에 관한 이슈를 파서 link 시키면 더 좋고요~
> 
> ![image](https://user-images.githubusercontent.com/43136096/146701244-50752868-3887-4d0c-ba2d-0ee6192d34b5.png)

의도대로 제대로 한 것인지는 잘 모르겠는데, 해당사항 표시해두었습니다~

2021-12-20 09:07 UTC, nhcho91 commented on src/construct_CTPG.jl
> +    id_nominal = max(round(Int, dim_ensemble / 2), 1)
ensemble_list에는 ensemble simulation 대상으로 고려할 초기조건 x0 값들의 list와 기준명령 r 값들의 list를 포함하고 있습니다. 
그러면 n개의 x0와 m개의 r 각각의 조합으로 이뤄진 mn개의 원소로 ensemble_list가 구성됩니다.
그 ensemble_list의 중간에 위치한 시뮬레이션 조건값에 해당하는 index를 대략 대표적인 조건값이다라고 생각하여 id_nominal로 해당 값을 가리킵니다.
progress plot에 ensemble 전체를 다 그리게 되면 알아보기 어렵고, 무거워져서 id_nominal에 대한 상태변수 궤적만 도시합니다.

2021-12-20 09:18 UTC, JinraeKim commented
@nhcho91 굳입니다~
참고로 [이런 식으로 내장 단어](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) 를 사용하면 알아서 link 가 됩니다.

#15 등을 참고 바랍니다.

2021-12-20 09:20 UTC, nhcho91 commented on src/construct_CTPG.jl
> +    @unpack ensemble_list, t_span, dim_x, dim_x_c = scenario
training scenario를 구성하는 변수들이라 생각해서 `scenario`라는 이름의 ComponentArray에 넣고 끄집어내고 있습니다~ 
(추천해준대로 곧 NamedTuple로 변경 예정)
그래서 각각을 `CTPG_train`의 인자로 받지 않아도 괜찮지 않을까요?

2021-12-20 09:22 UTC, nhcho91 commented on src/construct_CTPG.jl
> +            return [dx; dx_c; cost_running(t, x, y, u, r)]
추천사항의 의도를 잘 알겠는데...
type specification에 따라 AD의 정상 작동 여부가 확실치 않아서... 
그래서 미분되어야 하는 대상들에서는 웬만하면 ComponentArray를 일단 배제하고 있었습니다.
그러한 점을 감안해서 현재와 같이 작성하였습니다.

2021-12-20 09:22 UTC, nhcho91 commented on main/main_struct_CTPG_ensemble_autopilot.jl
> +    scenario = ComponentArray(ensemble_list = ensemble_list, t_span = t_span, dim_x = dim_x, dim_x_c = dim_x_c)
추천사항대로 변경하겠습니다.

2021-12-20 09:24 UTC, nhcho91 commented on src/construct_CTPG.jl
> +    prob_base = ODEProblem(fwd_dynamics(ensemble_list[id_nominal][2]), [ensemble_list[id_nominal][1]; zeros(Float32, dim_x_c + 1)], t_span, p_NN_0)
그렇지 않아도 고민하던 부분인데요,
처음에 구현한 버전에서는 x0_list와 r_list를 별도로 두었었네요
이 부분 ComponentArray로 처리해도 문제 없을지 확인해보고 반영하겠습니다.

2021-12-20 09:28 UTC, nhcho91 commented on src/construct_CTPG.jl
> +    end
매 iteration마다 여러 개의 앙상블에 대해 각각의 궤적을 구하고 그 결과를 활용하여 loss 값을 계산합니다.

그래서 당연히 learning iteration 숫자 max_iters와 맞춰도 됩니다. ㅎㅎ 250은 그냥 임의로 넣었던 값...

추천사항대로 변경하겠습니다.

2021-12-20 09:34 UTC, nhcho91 commented on src/construct_CTPG.jl
> +    result        = DiffEqFlux.sciml_train(loss, result_coarse.u, opt_2; cb = cb_progress, maxiters = 50)
`result_coarse`: ADAM 등 모멘텀 기반 1차 최적화 알고리즘으로 얻어진 거친 최적화 결과.
`result` : `result_coarse`의 최종결과를 초기값으로 시작하여 LBFGS 등 근사적인 뉴턴 알고리즘으로 얻어진 향상된 최적화 결과

이걸 굳이 이렇게 둔 것은 최적화 알고리즘의 특성 때문인데, ADAM 등은 계산이 상대적으로 가벼운 대신 곡률이 반영된 업데이트를 하지 않는 이유로 썩 좋은 파라미터 검색 영역으로 수렴하는데에는 유리하나, 어느 정도 수렴한 이후 정밀하게 최적값을 찾는데에는 한계가 있어서 
1차적 결과를 초기값으로 하는 2차 최적화를 수행합니다.

참고로 DiffEqFlux의 `sciml_train`에 인자로 사용할 최적화 알고리즘을 부여하지 않을 경우 위 설명과 비슷하게 ADAM->BFGS 순서로 이루어지는 최적화 알고리즘의 체인을 기본값으로 사용합니다.

2021-12-20 09:43 UTC, nhcho91 commented on src/construct_CTPG.jl
> +    solve_alg = Tsit5(), sense_alg = InterpolatingAdjoint(autojacvec = ZygoteVJP()), ensemble_alg = EnsembleThreads(), opt_1 = ADAM(0.01), opt_2 = LBFGS(), progress_plot = true, solve_kwargs...)
DiffEqFlux에서 기본값을 지원하기는 할텐데요, 
default key로 관심사인 제어 문제에 알맞는 알고리즘을 명시적으로 부여해주는 편이 낫지 않을까 판단하였습니다.

sensitivity analysis 알고리즘, 최적화 알고리즘 옵션 선택에 따라 안정성과 속도 차이가 있고 하다보니 뭔가 kwarg로 받는 게 좋을 것 같기는 한데....

묶어서 받는 편은 고민해보겠습니다.

2021-12-20 14:26 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    solve_alg = Tsit5(), sense_alg = InterpolatingAdjoint(autojacvec = ZygoteVJP()), ensemble_alg = EnsembleThreads(), opt_1 = ADAM(0.01), opt_2 = LBFGS(), progress_plot = true, solve_kwargs...)
그럼 "제어 문제에 알맞는 알고리즘을 명시적으로 부여했음"을 docstring 에 추가해주시겠어요?

그럼 나중에 추적이 더 쉬울 것 같습니다 ㅎㅎ

2021-12-20 14:27 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    id_nominal = max(round(Int, dim_ensemble / 2), 1)
오! 좋군요 ㅎㅎ
근데 중간값을 "중간 인덱스" 대신 "실제 medium에 가까운 값"으로 주면 좋을 것 같아요. 혹시 가능할까요?

2021-12-20 14:29 UTC, JinraeKim commented on src/construct_CTPG.jl
> +            return [dx; dx_c; cost_running(t, x, y, u, r)]
오 그렇군요...
ComponentArray 가 (아마) Array 랑 같게 작동하긴 할텐데, 저도 확신이 없어서 넘어가는게 좋겠습니다.
관련 테스트를 해봐도 좋을 것 같군요! #16에 관련 이슈를 생성했으니 이건 넘어가도 좋겠습니다.

2021-12-20 14:30 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    @unpack ensemble_list, t_span, dim_x, dim_x_c = scenario
하긴 현재로서는 코드 설계의 방향이 뚜렷하지 않으니 괜찮을 것 같아요!

2021-12-20 14:32 UTC, JinraeKim commented on src/construct_CTPG.jl
> +    result        = DiffEqFlux.sciml_train(loss, result_coarse.u, opt_2; cb = cb_progress, maxiters = 50)
오... 그렇군요!
ADAM -> BFGS 로 이루어지는 과정에 대한 문서 링크가 있을까요?
있다면 해당 내용을 docstring 에 추가하면 정말 좋을 것 같습니다!

2021-12-20 14:33 UTC, JinraeKim commented
@nhcho91 제가 모르는 부분이 많아 계속 질문하게 되네요 ㅋㅋㅋ 죄송합니다...

2021-12-20 15:37 UTC, nhcho91 commented on src/construct_CTPG.jl
> +    solve_alg = Tsit5(), sense_alg = InterpolatingAdjoint(autojacvec = ZygoteVJP()), ensemble_alg = EnsembleThreads(), opt_1 = ADAM(0.01), opt_2 = LBFGS(), progress_plot = true, solve_kwargs...)
추천해준대로 docstring 추가하였습니다

2021-12-20 15:38 UTC, nhcho91 commented on src/construct_CTPG.jl
> +    result        = DiffEqFlux.sciml_train(loss, result_coarse.u, opt_2; cb = cb_progress, maxiters = 50)
추천해준대로 docstring 추가하였습니다

2021-12-20 15:56 UTC, nhcho91 commented
새로 수정한 버전을 커밋하였습니다~

ComponentArray 사용 괜찮을 것 같기는 한데..  일단 배제하고 NamedTuple로 교체하여 접근되게끔 했습니다.

2021-12-21 04:49 UTC, JinraeKim approved these changes

2021-12-21 08:05 UTC, merged